/*
 * SPDX-FileCopyrightText: 2021-2024 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Unlicense OR CC0-1.0
 */

#include <stdint.h>
#include <stdlib.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "driver/i2s_std.h"
#include "driver/gpio.h"
#include "esp_check.h"
#include "sdkconfig.h"
#include <math.h>
#include "driver/ledc.h"
#include "i2s_std.h"

// pcm1808
#define I2S_ADC_STD_WS (4)    // I2S word select io number
#define I2S_ADC_STD_DIN (5)   // I2S data in io number
#define I2S_ADC_STD_BCLK (6)  // I2S bit clock io number
#define I2S_ADC_STD_DOUT (-1) // I2S data out io number

// pcm5102
#define I2S_DAC_STD_BCLK (16) // I2S bit clock io number
#define I2S_DAC_STD_DOUT (17) // I2S data out io number
#define I2S_DAC_STD_WS (18)   // I2S word select io number
#define I2S_DAC_STD_DIN (-1)  // I2S data in io number

#define GPIO_NUM_SCK (15)
#define GPIO_NUM_DEMP (8)
#define GPIO_NUM_XSMT (3)
#define GPIO_NUM_FMT (46)
#define GPIO_NUM_FLT (9)

static i2s_chan_handle_t tx_chan; // I2S tx channel handler
static i2s_chan_handle_t rx_chan; // I2S rx channel handler
QueueHandle_t audio_queue = NULL;
static const char *TAG = "i2s_std";

static void i2s_read_task(void *args)
{
    uint8_t *r_buf = (uint8_t *)calloc(1, BUFF_SIZE);
    assert(r_buf); // Check if r_buf allocation success
    size_t r_bytes = 0;
    size_t w_bytes = 0;
    audio_data_t audio_data = {0};

    while (1)
    {
        /* Read i2s data */
        if (i2s_channel_read(rx_chan, r_buf, BUFF_SIZE, &r_bytes, 1000) == ESP_OK)
        {
            audio_data.size = r_bytes;
            memcpy(audio_data.samples, r_buf, r_bytes);
            xQueueSendToBack(audio_queue, &audio_data, pdMS_TO_TICKS(0));
            /* Write i2s data */
            if (i2s_channel_write(tx_chan, audio_data.samples, audio_data.size, &w_bytes, 1000) == ESP_OK)
            {
                // printf("Write Task: i2s write %d bytes\n", w_bytes);
            }
            else
            {
                printf("Write Task: i2s write failed\n");
            }
        }
        else
        {
            printf("Read Task: i2s read failed\n");
        }
    }
    free(r_buf);
    vTaskDelete(NULL);
}

static void play_boot_music(void)
{
    extern const unsigned char boot_wav_start[] asm("_binary_boot_wav_start");
    extern const unsigned char boot_wav_end[] asm("_binary_boot_wav_end");
    const size_t boot_wav_size = (boot_wav_end - boot_wav_start);
    size_t w_bytes = 0;
    int32_t audio[64] = {0};
    ESP_LOGI(TAG, "Play boot music");
    for (int i = 44; i < boot_wav_size; i += 128)
    {
        for (int j = 0, k = 0; j < 128; j += 2, k++)
        {
            const unsigned char *bytes = boot_wav_start + i + j;
            int16_t data = (int16_t)((bytes[1] << 8) | (bytes[0] & 0xFF));
            audio[k] = data * 65535;
        }
        // Write to DAC
        if (i2s_channel_write(tx_chan, (char *)audio, sizeof(audio), &w_bytes, 1000) == ESP_OK)
        {
            // printf("Write Task: i2s write %d bytes\n", w_bytes);
        }
        else
        {
            printf("Write Task: i2s write failed\n");
        }
    }
    ESP_LOGI(TAG, "Play boot music completed");
}

static void i2s_init_std_simplex(void)
{
    /* Setp 1: Determine the I2S channel configuration and allocate two channels one by one
     * The default configuration can be generated by the helper macro,
     * it only requires the I2S controller id and I2S role
     * The tx and rx channels here are registered on different I2S controller,
     * Except ESP32 and ESP32-S2, others allow to register two separate tx & rx channels on a same controller */
    i2s_chan_config_t tx_chan_cfg = I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_0, I2S_ROLE_MASTER);
    ESP_ERROR_CHECK(i2s_new_channel(&tx_chan_cfg, &tx_chan, NULL));
    i2s_chan_config_t rx_chan_cfg = I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_1, I2S_ROLE_MASTER);
    ESP_ERROR_CHECK(i2s_new_channel(&rx_chan_cfg, NULL, &rx_chan));

    /* Step 2: Setting the configurations of standard mode and initialize each channels one by one
     * The slot configuration and clock configuration can be generated by the macros
     * These two helper macros is defined in 'i2s_std.h' which can only be used in STD mode.
     * They can help to specify the slot and clock configurations for initialization or re-configuring */
    i2s_std_config_t tx_std_cfg = {
        .clk_cfg = I2S_STD_CLK_DEFAULT_CONFIG(48000),
        .slot_cfg = I2S_STD_PHILIPS_SLOT_DEFAULT_CONFIG(I2S_DATA_BIT_WIDTH_32BIT, I2S_SLOT_MODE_STEREO),
        .gpio_cfg = {
            .mclk = I2S_GPIO_UNUSED, // some codecs may require mclk signal, this example doesn't need it
            .bclk = I2S_DAC_STD_BCLK,
            .ws = I2S_DAC_STD_WS,
            .dout = I2S_DAC_STD_DOUT,
            .din = I2S_DAC_STD_DIN,
            .invert_flags = {
                .mclk_inv = false,
                .bclk_inv = false,
                .ws_inv = false,
            },
        },
    };
    ESP_ERROR_CHECK(i2s_channel_init_std_mode(tx_chan, &tx_std_cfg));
    /* Enable the TX channel */
    ESP_ERROR_CHECK(i2s_channel_enable(tx_chan));

    i2s_std_config_t rx_std_cfg = {
        .clk_cfg = I2S_STD_CLK_DEFAULT_CONFIG(48000),
        .slot_cfg = I2S_STD_PHILIPS_SLOT_DEFAULT_CONFIG(I2S_DATA_BIT_WIDTH_32BIT, I2S_SLOT_MODE_STEREO),
        .gpio_cfg = {
            .mclk = I2S_GPIO_UNUSED, // some codecs may require mclk signal, this example doesn't need it
            .bclk = I2S_ADC_STD_BCLK,
            .ws = I2S_ADC_STD_WS,
            .dout = I2S_ADC_STD_DOUT,
            .din = I2S_ADC_STD_DIN,
            .invert_flags = {
                .mclk_inv = false,
                .bclk_inv = false,
                .ws_inv = false,
            },
        },
    };
    ESP_ERROR_CHECK(i2s_channel_init_std_mode(rx_chan, &rx_std_cfg));
    /* Enable the RX channel */
    ESP_ERROR_CHECK(i2s_channel_enable(rx_chan));
}

void initPcm5102Options()
{
    esp_rom_gpio_pad_select_gpio(GPIO_NUM_SCK);
    gpio_set_direction(GPIO_NUM_SCK, GPIO_MODE_OUTPUT);
    gpio_set_level(GPIO_NUM_SCK, 1); // 设置GPIO状态，0为低电平，非0为高电平

    esp_rom_gpio_pad_select_gpio(GPIO_NUM_DEMP);
    gpio_set_direction(GPIO_NUM_DEMP, GPIO_MODE_OUTPUT);
    gpio_set_level(GPIO_NUM_DEMP, 1); // 44.1-kHz采样率的减重控制:关(低)/开(高)

    esp_rom_gpio_pad_select_gpio(GPIO_NUM_XSMT);
    gpio_set_direction(GPIO_NUM_XSMT, GPIO_MODE_OUTPUT);
    gpio_set_level(GPIO_NUM_XSMT, 1); // 软静音控制:软静音(低)/软不静音(高)

    esp_rom_gpio_pad_select_gpio(GPIO_NUM_FMT);
    gpio_set_direction(GPIO_NUM_FMT, GPIO_MODE_OUTPUT);
    gpio_set_level(GPIO_NUM_FMT, 0); // 音频格式选择:I2S(低)/左对齐(高)

    esp_rom_gpio_pad_select_gpio(GPIO_NUM_FLT);
    gpio_set_direction(GPIO_NUM_FLT, GPIO_MODE_OUTPUT);
    gpio_set_level(GPIO_NUM_FLT, 1); // 过滤器选择:正常延迟(低)/低延迟(高)
}

void i2s_app_main(void)
{
    initPcm5102Options();
    i2s_init_std_simplex();
    play_boot_music();
    audio_queue = xQueueCreate(AUDIO_QUEUE_SIZE, sizeof(audio_data_t));
    xTaskCreate(i2s_read_task, "i2s_read_task", 4096, NULL, 5, NULL);
}
