/*
 * SPDX-FileCopyrightText: 2021-2024 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Unlicense OR CC0-1.0
 */

#include <stdint.h>
#include <stdlib.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "driver/i2s_std.h"
#include "driver/gpio.h"
#include "esp_check.h"
#include "sdkconfig.h"
#include <math.h>
#include "i2s_std.h"

/* Set 1 to allocate rx & tx channels in duplex mode on a same I2S controller, they will share the BCLK and WS signal
 * Set 0 to allocate rx & tx channels in simplex mode, these two channels will be totally separated,
 * Specifically, due to the hardware limitation, the simplex rx & tx channels can't be registered on the same controllers on ESP32 and ESP32-S2,
 * and ESP32-S2 has only one I2S controller, so it can't allocate two simplex channels */

#define I2S_DAC_STD_BCLK (6) // I2S bit clock io number
#define I2S_DAC_STD_WS (4)   // I2S word select io number
#define I2S_DAC_STD_DOUT (5) // I2S data out io number
#define I2S_DAC_STD_DIN (-1) // I2S data in io number

#define I2S_ADC_STD_BCLK (17) // I2S bit clock io number
#define I2S_ADC_STD_WS (18)   // I2S word select io number
#define I2S_ADC_STD_DOUT (-1) // I2S data out io number
#define I2S_ADC_STD_DIN (16)  // I2S data in io number

static i2s_chan_handle_t tx_chan; // I2S tx channel handler
static i2s_chan_handle_t rx_chan; // I2S rx channel handler
QueueHandle_t audio_queue = NULL;

static void i2s_read_task(void *args)
{
    uint8_t *r_buf = (uint8_t *)calloc(1, BUFF_SIZE);
    assert(r_buf); // Check if r_buf allocation success
    size_t r_bytes = 0;
    size_t w_bytes = 0;
    audio_data_t audio_data = {0};

    /* (Optional) Preload the data before enabling the TX channel, so that the valid data can be transmitted immediately */

    /* Here we load the target buffer repeatedly, until all the DMA buffers are preloaded */
    // ESP_ERROR_CHECK(i2s_channel_preload_data(tx_chan, audio_data.samples, EXAMPLE_BUFF_SIZE, &w_bytes));

    /* ATTENTION: The print and delay in the read task only for monitoring the data by human,
     * Normally there shouldn't be any delays to ensure a short polling time,
     * Otherwise the dma buffer will overflow and lead to the data lost */
    while (1)
    {
        /* Read i2s data */
        if (i2s_channel_read(rx_chan, r_buf, BUFF_SIZE, &r_bytes, 1000) == ESP_OK)
        {
            audio_data.size = r_bytes;
            memcpy(audio_data.samples, r_buf, r_bytes);
            xQueueSendToBack(audio_queue, &audio_data, pdMS_TO_TICKS(0));
            /* Write i2s data */
            if (i2s_channel_write(tx_chan, audio_data.samples, audio_data.size, &w_bytes, 1000) == ESP_OK)
            {
                // printf("Write Task: i2s write %d bytes\n", w_bytes);
            }
            else
            {
                printf("Write Task: i2s write failed\n");
            }
        }
        else
        {
            printf("Read Task: i2s read failed\n");
        }
    }
    free(r_buf);
    vTaskDelete(NULL);
}

static void i2s_init_std_simplex(void)
{
    /* Setp 1: Determine the I2S channel configuration and allocate two channels one by one
     * The default configuration can be generated by the helper macro,
     * it only requires the I2S controller id and I2S role
     * The tx and rx channels here are registered on different I2S controller,
     * Except ESP32 and ESP32-S2, others allow to register two separate tx & rx channels on a same controller */
    i2s_chan_config_t tx_chan_cfg = I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_0, I2S_ROLE_MASTER);
    ESP_ERROR_CHECK(i2s_new_channel(&tx_chan_cfg, &tx_chan, NULL));
    i2s_chan_config_t rx_chan_cfg = I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_1, I2S_ROLE_SLAVE);
    ESP_ERROR_CHECK(i2s_new_channel(&rx_chan_cfg, NULL, &rx_chan));

    /* Step 2: Setting the configurations of standard mode and initialize each channels one by one
     * The slot configuration and clock configuration can be generated by the macros
     * These two helper macros is defined in 'i2s_std.h' which can only be used in STD mode.
     * They can help to specify the slot and clock configurations for initialization or re-configuring */
    i2s_std_config_t tx_std_cfg = {
        .clk_cfg = I2S_STD_CLK_DEFAULT_CONFIG(48000),
        .slot_cfg = I2S_STD_PHILIPS_SLOT_DEFAULT_CONFIG(I2S_DATA_BIT_WIDTH_32BIT, I2S_SLOT_MODE_STEREO),
        .gpio_cfg = {
            .mclk = I2S_GPIO_UNUSED, // some codecs may require mclk signal, this example doesn't need it
            .bclk = I2S_DAC_STD_BCLK,
            .ws = I2S_DAC_STD_WS,
            .dout = I2S_DAC_STD_DOUT,
            .din = I2S_DAC_STD_DIN,
            .invert_flags = {
                .mclk_inv = false,
                .bclk_inv = false,
                .ws_inv = false,
            },
        },
    };
    ESP_ERROR_CHECK(i2s_channel_init_std_mode(tx_chan, &tx_std_cfg));
    /* Enable the TX channel */
    ESP_ERROR_CHECK(i2s_channel_enable(tx_chan));

    i2s_std_config_t rx_std_cfg = {
        .clk_cfg = I2S_STD_CLK_DEFAULT_CONFIG(48000),
        .slot_cfg = I2S_STD_PHILIPS_SLOT_DEFAULT_CONFIG(I2S_DATA_BIT_WIDTH_32BIT, I2S_SLOT_MODE_STEREO),
        .gpio_cfg = {
            .mclk = I2S_GPIO_UNUSED, // some codecs may require mclk signal, this example doesn't need it
            .bclk = I2S_ADC_STD_BCLK,
            .ws = I2S_ADC_STD_WS,
            .dout = I2S_ADC_STD_DOUT,
            .din = I2S_ADC_STD_DIN,
            .invert_flags = {
                .mclk_inv = false,
                .bclk_inv = false,
                .ws_inv = false,
            },
        },
    };
    ESP_ERROR_CHECK(i2s_channel_init_std_mode(rx_chan, &rx_std_cfg));
    /* Enable the RX channel */
    ESP_ERROR_CHECK(i2s_channel_enable(rx_chan));
}

void i2s_app_main(void)
{
    i2s_init_std_simplex();
    audio_queue = xQueueCreate(AUDIO_QUEUE_SIZE, sizeof(audio_data_t));
    xTaskCreate(i2s_read_task, "i2s_read_task", 4096, NULL, 5, NULL);
}
